# Copyright 2024 Mist Tecnologia LTDA. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y rsync
      - run:
          command: |
            curl -s "https://fuchsia.googlesource.com/jiri/+/HEAD/scripts/bootstrap_jiri?format=TEXT" | base64 --decode | bash -s .
            export PATH=$PWD/.jiri_root/bin:$PATH
            jiri import -name=integration flower https://github.com/misttech/integration
      - restore_cache:
          name: Restore Jiri Cache
          keys:
            - &jiri-cache jiri-packages-{{ checksum "integration/jiri.lock" }}
            - jiri-packages
      - run:
          command: |
            export PATH=$PWD/.jiri_root/bin:$PATH
            jiri update -v -vv
            git checkout $CIRCLE_BRANCH
      - save_cache:
          name: Save Jiri Package Cache
          key: *jiri-cache
          paths:
            - .cipd
            - prebuilt
      - run: make test && make ci

workflows:
  build-workflow:
    jobs:
      - build
